export const countryConstants = [
    { name: "Afghanistan", isoCode: "AF", currency: "AFN", mobileCode: "+93" },
    { name: "Albania", isoCode: "AL", currency: "ALL", mobileCode: "+355" },
    { name: "Algeria", isoCode: "DZ", currency: "DZD", mobileCode: "+213" },
    { name: "Andorra", isoCode: "AD", currency: "EUR", mobileCode: "+376" },
    { name: "Angola", isoCode: "AO", currency: "AOA", mobileCode: "+244" },
    { name: "Antigua and Barbuda", isoCode: "AG", currency: "XCD", mobileCode: "+1-268" },
    { name: "Argentina", isoCode: "AR", currency: "ARS", mobileCode: "+54" },
    { name: "Armenia", isoCode: "AM", currency: "AMD", mobileCode: "+374" },
    { name: "Australia", isoCode: "AU", currency: "AUD", mobileCode: "+61" },
    { name: "Austria", isoCode: "AT", currency: "EUR", mobileCode: "+43" },
    { name: "Azerbaijan", isoCode: "AZ", currency: "AZN", mobileCode: "+994" },
    { name: "Bahamas", isoCode: "BS", currency: "BSD", mobileCode: "+1-242" },
    { name: "Bahrain", isoCode: "BH", currency: "BHD", mobileCode: "+973" },
    { name: "Bangladesh", isoCode: "BD", currency: "BDT", mobileCode: "+880" },
    { name: "Barbados", isoCode: "BB", currency: "BBD", mobileCode: "+1-246" },
    { name: "Belarus", isoCode: "BY", currency: "BYN", mobileCode: "+375" },
    { name: "Belgium", isoCode: "BE", currency: "EUR", mobileCode: "+32" },
    { name: "Belize", isoCode: "BZ", currency: "BZD", mobileCode: "+501" },
    { name: "Benin", isoCode: "BJ", currency: "CFA", mobileCode: "+229" },
    { name: "Bhutan", isoCode: "BT", currency: "BTN", mobileCode: "+975" },
    { name: "Bolivia", isoCode: "BO", currency: "BOB", mobileCode: "+591" },
    { name: "Bosnia and Herzegovina", isoCode: "BA", currency: "BAM", mobileCode: "+387" },
    { name: "Botswana", isoCode: "BW", currency: "BWP", mobileCode: "+267" },
    { name: "Brazil", isoCode: "BR", currency: "BRL", mobileCode: "+55" },
    { name: "Brunei Darussalam", isoCode: "BN", currency: "BND", mobileCode: "+673" },
    { name: "Bulgaria", isoCode: "BG", currency: "BGN", mobileCode: "+359" },
    { name: "Burkina Faso", isoCode: "BF", currency: "BFW", mobileCode: "+226" },
    { name: "Burundi", isoCode: "BI", currency: "BIF", mobileCode: "+257" },
    { name: "Cabo Verde", isoCode: "CV", currency: "CVE", mobileCode: "+238" },
    { name: "Cambodia", isoCode: "KH", currency: "KHR", mobileCode: "+855" },
    { name: "Cameroon", isoCode: "CM", currency: "CFA", mobileCode: "+237" },
    { name: "Canada", isoCode: "CA", currency: "CAD", mobileCode: "+1" },
    { name: "Central African Republic", isoCode: "CF", currency: "CAF", mobileCode: "+236" },
    { name: "Chad", isoCode: "TD", currency: "CFA", mobileCode: "+235" },
    { name: "Chile", isoCode: "CL", currency: "CLP", mobileCode: "+56" },
    { name: "China", isoCode: "CN", currency: "CNY", mobileCode: "+86" },
    { name: "Colombia", isoCode: "CO", currency: "COP", mobileCode: "+57" },
    { name: "Comoros", isoCode: "KM", currency: "COM", mobileCode: "+269" },
    { name: "Congo (Congo-Brazzaville)", isoCode: "CG", currency: "CDF", mobileCode: "+242" },
    { name: "Congo (Democratic Republic of the Congo)", isoCode: "CD", currency: "CDF", mobileCode: "+243" },
    { name: "Costa Rica", isoCode: "CR", currency: "CRC", mobileCode: "+506" },
    { name: "Croatia", isoCode: "HR", currency: "HRK", mobileCode: "+385" },
    { name: "Cuba", isoCode: "CU", currency: "CUP", mobileCode: "+53" },
    { name: "Cyprus", isoCode: "CY", currency: "CYP", mobileCode: "+357" },
    { name: "Czech Republic", isoCode: "CZ", currency: "CZK", mobileCode: "+420" },
    { name: "Denmark", isoCode: "DK", currency: "DKK", mobileCode: "+45" },
    { name: "Djibouti", isoCode: "DJ", currency: "DJF", mobileCode: "+253" },
    { name: "Dominica", isoCode: "DM", currency: "XCD", mobileCode: "+1-767" },
    { name: "Dominican Republic", isoCode: "DO", currency: "DOP", mobileCode: "+1-809" },
    { name: "Ecuador", isoCode: "EC", currency: "USD", mobileCode: "+593" },
    { name: "Egypt", isoCode: "EG", currency: "EGP", mobileCode: "+20" },
    { name: "El Salvador", isoCode: "SV", currency: "SVC", mobileCode: "+503" },
    { name: "Equatorial Guinea", isoCode: "GQ", currency: "GNF", mobileCode: "+240" },
    { name: "Eritrea", isoCode: "ER", currency: "ERN", mobileCode: "+291" },
    { name: "Estonia", isoCode: "EE", currency: "EEK", mobileCode: "+372" },
    { name: "Eswatini", isoCode: "SZ", currency: "SZL", mobileCode: "+268" },
    { name: "Ethiopia", isoCode: "ET", currency: "ETB", mobileCode: "+251" },
    { name: "Fiji", isoCode: "FJ", currency: "FJD", mobileCode: "+679" },
    { name: "Finland", isoCode: "FI", currency: "EUR", mobileCode: "+358" },
    { name: "France", isoCode: "FR", currency: "EUR", mobileCode: "+33" },
    { name: "Gabon", isoCode: "GA", currency: "GAB", mobileCode: "+241" },
    { name: "Gambia", isoCode: "GM", currency: "GMD", mobileCode: "+220" },
    { name: "Georgia", isoCode: "GE", currency: "GEL", mobileCode: "+995" },
    { name: "Germany", isoCode: "DE", currency: "EUR", mobileCode: "+49" },
    { name: "Ghana", isoCode: "GH", currency: "GHS", mobileCode: "+233" },
    { name: "Greece", isoCode: "GR", currency: "EUR", mobileCode: "+30" },
    { name: "Grenada", isoCode: "GD", currency: "XCD", mobileCode: "+1-473" },
    { name: "Guatemala", isoCode: "GT", currency: "GTQ", mobileCode: "+502" },
    { name: "Guinea", isoCode: "GN", currency: "GNF", mobileCode: "+224" },
    { name: "Guinea-Bissau", isoCode: "GW", currency: "GNF", mobileCode: "+245" },
    { name: "Guyana", isoCode: "GY", currency: "GYD", mobileCode: "+592" },
    { name: "Haiti", isoCode: "HT", currency: "HTG", mobileCode: "+509" },
    { name: "Honduras", isoCode: "HN", currency: "HNL", mobileCode: "+504" },
    { name: "Hungary", isoCode: "HU", currency: "HUF", mobileCode: "+36" },
    { name: "Iceland", isoCode: "IS", currency: "ISK", mobileCode: "+354" },
    { name: "India", isoCode: "IN", currency: "INR", mobileCode: "+91" },
    { name: "Indonesia", isoCode: "ID", currency: "IDR", mobileCode: "+62" },
    { name: "Iran", isoCode: "IR", currency: "IRR", mobileCode: "+98" },
    { name: "Iraq", isoCode: "IQ", currency: "IQD", mobileCode: "+964" },
    { name: "Ireland", isoCode: "IE", currency: "EUR", mobileCode: "+353" },
    { name: "Israel", isoCode: "IL", currency: "ILS", mobileCode: "+972" },
    { name: "Italy", isoCode: "IT", currency: "EUR", mobileCode: "+39" },
    { name: "Jamaica", isoCode: "JM", currency: "JMD", mobileCode: "+1-876" },
    { name: "Japan", isoCode: "JP", currency: "JPY", mobileCode: "+81" },
    { name: "Jordan", isoCode: "JO", currency: "JOD", mobileCode: "+962" },
    { name: "Kazakhstan", isoCode: "KZ", currency: "KZT", mobileCode: "+7" },
    { name: "Kenya", isoCode: "KE", currency: "KES", mobileCode: "+254" },
    { name: "Kiribati", isoCode: "KI", currency: "AUD", mobileCode: "+686" },
    { name: "Korea (North)", isoCode: "KP", currency: "KPW", mobileCode: "+850" },
    { name: "Korea (South)", isoCode: "KR", currency: "KRW", mobileCode: "+82" },
    { name: "Kuwait", isoCode: "KW", currency: "KWD", mobileCode: "+965" },
    { name: "Kyrgyzstan", isoCode: "KG", currency: "KGS", mobileCode: "+996" },
    { name: "Laos", isoCode: "LA", currency: "LAK", mobileCode: "+856" },
    { name: "Latvia", isoCode: "LV", currency: "EUR", mobileCode: "+371" },
    { name: "Lebanon", isoCode: "LB", currency: "LBP", mobileCode: "+961" },
    { name: "Lesotho", isoCode: "LS", currency: "LSL", mobileCode: "+266" },
    { name: "Liberia", isoCode: "LR", currency: "LRD", mobileCode: "+231" },
    { name: "Libya", isoCode: "LY", currency: "LYD", mobileCode: "+218" },
    { name: "Liechtenstein", isoCode: "LI", currency: "CHF", mobileCode: "+423" },
    { name: "Lithuania", isoCode: "LT", currency: "EUR", mobileCode: "+370" },
    { name: "Luxembourg", isoCode: "LU", currency: "EUR", mobileCode: "+352" },
    { name: "Madagascar", isoCode: "MG", currency: "MGA", mobileCode: "+261" },
    { name: "Malawi", isoCode: "MW", currency: "MWK", mobileCode: "+265" },
    { name: "Malaysia", isoCode: "MY", currency: "MYR", mobileCode: "+60" },
    { name: "Maldives", isoCode: "MV", currency: "MVR", mobileCode: "+960" },
    { name: "Mali", isoCode: "ML", currency: "XOF", mobileCode: "+223" },
    { name: "Malta", isoCode: "MT", currency: "EUR", mobileCode: "+356" },
    { name: "Marshall Islands", isoCode: "MH", currency: "USD", mobileCode: "+692" },
    { name: "Mauritania", isoCode: "MR", currency: "MRO", mobileCode: "+222" },
    { name: "Mauritius", isoCode: "MU", currency: "MUR", mobileCode: "+230" },
    { name: "Mexico", isoCode: "MX", currency: "MXN", mobileCode: "+52" },
    { name: "Micronesia", isoCode: "FM", currency: "USD", mobileCode: "+691" },
    { name: "Moldova", isoCode: "MD", currency: "MDL", mobileCode: "+373" },
    { name: "Monaco", isoCode: "MC", currency: "EUR", mobileCode: "+377" },
    { name: "Mongolia", isoCode: "MN", currency: "MNT", mobileCode: "+976" },
    { name: "Montenegro", isoCode: "ME", currency: "EUR", mobileCode: "+382" },
    { name: "Morocco", isoCode: "MA", currency: "MAD", mobileCode: "+212" },
    { name: "Mozambique", isoCode: "MZ", currency: "MZN", mobileCode: "+258" },
    { name: "Myanmar (Burma)", isoCode: "MM", currency: "MMK", mobileCode: "+95" },
    { name: "Namibia", isoCode: "NA", currency: "NAD", mobileCode: "+264" },
    { name: "Nauru", isoCode: "NR", currency: "AUD", mobileCode: "+674" },
    { name: "Nepal", isoCode: "NP", currency: "NPR", mobileCode: "+977" },
    { name: "Netherlands", isoCode: "NL", currency: "EUR", mobileCode: "+31" },
    { name: "New Zealand", isoCode: "NZ", currency: "NZD", mobileCode: "+64" },
    { name: "Nicaragua", isoCode: "NI", currency: "NIO", mobileCode: "+505" },
    { name: "Niger", isoCode: "NE", currency: "NGN", mobileCode: "+227" },
    { name: "Nigeria", isoCode: "NG", currency: "NGN", mobileCode: "+234" },
    { name: "North Macedonia", isoCode: "MK", currency: "MKD", mobileCode: "+389" },
    { name: "Norway", isoCode: "NO", currency: "NOK", mobileCode: "+47" },
    { name: "Oman", isoCode: "OM", currency: "OMR", mobileCode: "+968" },
    { name: "Pakistan", isoCode: "PK", currency: "PKR", mobileCode: "+92" },
    { name: "Palau", isoCode: "PW", currency: "USD", mobileCode: "+680" },
    { name: "Panama", isoCode: "PA", currency: "PAB", mobileCode: "+507" },
    { name: "Papua New Guinea", isoCode: "PG", currency: "PGK", mobileCode: "+675" },
    { name: "Paraguay", isoCode: "PY", currency: "PYG", mobileCode: "+595" },
    { name: "Peru", isoCode: "PE", currency: "PEN", mobileCode: "+51" },
    { name: "Philippines", isoCode: "PH", currency: "PHP", mobileCode: "+63" },
    { name: "Poland", isoCode: "PL", currency: "PLN", mobileCode: "+48" },
    { name: "Portugal", isoCode: "PT", currency: "EUR", mobileCode: "+351" },
    { name: "Qatar", isoCode: "QA", currency: "QAR", mobileCode: "+974" },
    { name: "Romania", isoCode: "RO", currency: "RON", mobileCode: "+40" },
    { name: "Russia", isoCode: "RU", currency: "RUB", mobileCode: "+7" },
    { name: "Rwanda", isoCode: "RW", currency: "RWF", mobileCode: "+250" },
    { name: "Saint Kitts and Nevis", isoCode: "KN", currency: "XCD", mobileCode: "+1-869" },
    { name: "Saint Lucia", isoCode: "LC", currency: "XCD", mobileCode: "+1-758" },
    { name: "Saint Vincent and the Grenadines", isoCode: "VC", currency: "XCD", mobileCode: "+1-784" },
    { name: "Samoa", isoCode: "WS", currency: "WST", mobileCode: "+685" },
    { name: "San Marino", isoCode: "SM", currency: "EUR", mobileCode: "+378" },
    { name: "Sao Tome and Principe", isoCode: "ST", currency: "STN", mobileCode: "+239" },
    { name: "Saudi Arabia", isoCode: "SA", currency: "SAR", mobileCode: "+966" },
    { name: "Senegal", isoCode: "SN", currency: "XOF", mobileCode: "+221" },
    { name: "Serbia", isoCode: "RS", currency: "RSD", mobileCode: "+381" },
    { name: "Seychelles", isoCode: "SC", currency: "SCR", mobileCode: "+248" },
    { name: "Sierra Leone", isoCode: "SL", currency: "SLL", mobileCode: "+232" },
    { name: "Singapore", isoCode: "SG", currency: "SGD", mobileCode: "+65" },
    { name: "Slovakia", isoCode: "SK", currency: "EUR", mobileCode: "+421" },
    { name: "Slovenia", isoCode: "SI", currency: "EUR", mobileCode: "+386" },
    { name: "Solomon Islands", isoCode: "SB", currency: "SBD", mobileCode: "+677" },
    { name: "Somalia", isoCode: "SO", currency: "SOS", mobileCode: "+252" },
    { name: "South Africa", isoCode: "ZA", currency: "ZAR", mobileCode: "+27" },
    { name: "South Sudan", isoCode: "SS", currency: "SSP", mobileCode: "+211" },
    { name: "Spain", isoCode: "ES", currency: "EUR", mobileCode: "+34" },
    { name: "Sri Lanka", isoCode: "LK", currency: "LKR", mobileCode: "+94" },
    { name: "Sudan", isoCode: "SD", currency: "SDG", mobileCode: "+249" },
    { name: "Suriname", isoCode: "SR", currency: "SRD", mobileCode: "+597" },
    { name: "Sweden", isoCode: "SE", currency: "SEK", mobileCode: "+46" },
    { name: "Switzerland", isoCode: "CH", currency: "CHF", mobileCode: "+41" },
    { name: "Syria", isoCode: "SY", currency: "SYP", mobileCode: "+963" },
    { name: "Taiwan", isoCode: "TW", currency: "TWD", mobileCode: "+886" },
    { name: "Tajikistan", isoCode: "TJ", currency: "TJS", mobileCode: "+992" },
    { name: "Tanzania", isoCode: "TZ", currency: "TZS", mobileCode: "+255" },
    { name: "Thailand", isoCode: "TH", currency: "THB", mobileCode: "+66" },
    { name: "Timor-Leste", isoCode: "TL", currency: "USD", mobileCode: "+670" },
    { name: "Togo", isoCode: "TG", currency: "XOF", mobileCode: "+228" },
    { name: "Tonga", isoCode: "TO", currency: "TOP", mobileCode: "+676" },
    { name: "Trinidad and Tobago", isoCode: "TT", currency: "TTD", mobileCode: "+1-868" },
    { name: "Tunisia", isoCode: "TN", currency: "TND", mobileCode: "+216" },
    { name: "Turkey", isoCode: "TR", currency: "TRY", mobileCode: "+90" },
    { name: "Turkmenistan", isoCode: "TM", currency: "TMT", mobileCode: "+993" },
    { name: "Tuvalu", isoCode: "TV", currency: "AUD", mobileCode: "+688" },
    { name: "Uganda", isoCode: "UG", currency: "UGX", mobileCode: "+256" },
    { name: "Ukraine", isoCode: "UA", currency: "UAH", mobileCode: "+380" },
    { name: "United Arab Emirates", isoCode: "AE", currency: "AED", mobileCode: "+971" },
    { name: "United Kingdom", isoCode: "GB", currency: "GBP", mobileCode: "+44" },
    { name: "United States", isoCode: "US", currency: "USD", mobileCode: "+1" },
    { name: "Uruguay", isoCode: "UY", currency: "UYU", mobileCode: "+598" },
    { name: "Uzbekistan", isoCode: "UZ", currency: "UZS", mobileCode: "+998" },
    { name: "Vanuatu", isoCode: "VU", currency: "VUV", mobileCode: "+678" },
    { name: "Vatican City", isoCode: "VA", currency: "EUR", mobileCode: "+379" },
    { name: "Venezuela", isoCode: "VE", currency: "VES", mobileCode: "+58" },
    { name: "Vietnam", isoCode: "VN", currency: "VND", mobileCode: "+84" },
    { name: "Yemen", isoCode: "YE", currency: "YER", mobileCode: "+967" },
    { name: "Zambia", isoCode: "ZM", currency: "ZMW", mobileCode: "+260" },
    { name: "Zimbabwe", isoCode: "ZW", currency: "ZWL", mobileCode: "+263" }       
]  