export const destinationData = {
    name: "India",
    currency: "INR",
    timezone: "UTC+05:30",
    tripDuration: ["5-15 days"],
    description: "Explore the diverse culture, history, and natural beauty of India.",
    visaType: "tourist",
    country: "India",
    continent: "Asia",
    latitude: 20.5937,
    longitude: 78.9629,
    markup: 15,
  };
  
  export const citiesData = [
    { name: "New Delhi", iataCode: "DEL", latitude: 28.6139, longitude: 77.2090, languageSpoken: "Hindi, English", hotelApiCityName: "New Delhi,   DELHI" },
    { name: "Mumbai", iataCode: "BOM", latitude: 19.0760, longitude: 72.8777, languageSpoken: "Hindi, English", hotelApiCityName: "Mumbai,   Maharashtra" },
    { name: "Jaipur", iataCode: "JAI", latitude: 26.9124, longitude: 75.7873, languageSpoken: "Hindi, English", hotelApiCityName: "Jaipur,   Rajasthan" },
    { name: "Bangalore", iataCode: "BLR", latitude: 12.9716, longitude: 77.5946, languageSpoken: "Hindi, English", hotelApiCityName: "Banagalore,   Karnataka" },
    { name: "Chennai", iataCode: "MAA", latitude: 13.0827, longitude: 80.2707, languageSpoken: "Hindi, English", hotelApiCityName: "Chennai,   Tamil Nadu" },
    { name: "Kolkata", iataCode: "CCU", latitude: 22.5726, longitude: 88.3639, languageSpoken: "Hindi, English", hotelApiCityName: "Calcutta,   West Bengal" },
    { name: "Ahemdabad", iataCode: "AMD", latitude: 23.0225, longitude: 72.5714, languageSpoken: "Hindi, English", hotelApiCityName: "Kutch,   Gujrat" },
  ];
  
  export const activitiesData = [
    {
      name: "Visit Qutub Minar",
      cityName: "New Delhi",
      duration: "2 hours",
      featured: true,
      opensAt: "09:00",
      closesAt: "17:00",
      physicalDifficulty: "Easy",
      localGuidesAvailable: true,
      isFamilyFriendly: true,
      refundable: true,
      price: "500",
    },
    {
      name: "Mumbai Darshan",
      cityName: "Mumbai",
      duration: "2 hours",
      featured: true,
      opensAt: "06:00",
      closesAt: "10:00",
      physicalDifficulty: "Easy",
      localGuidesAvailable: false,
      isFamilyFriendly: true,
      refundable: false,
      price: "200",
    },
    {
      name: "Explore Lalbagh Botanical Garden",
      cityName: "Bangalore",
      duration: "3 hours",
      featured: true,
      opensAt: "08:00",
      closesAt: "18:00",
      physicalDifficulty: "Moderate",
      localGuidesAvailable: true,
      isFamilyFriendly: true,
      refundable: true,
      price: "300",
    },
    {
      name: "Amer Fort Tour",
      cityName: "Jaipur",
      duration: "4 hours",
      featured: true,
      opensAt: "10:00",
      closesAt: "17:00",
      physicalDifficulty: "Moderate",
      localGuidesAvailable: true,
      isFamilyFriendly: true,
      refundable: false,
      price: "700",
    },
    {
      name: "Elephant Ride at Amer Fort",
      cityName: "Jaipur",
      duration: "1 hour",
      featured: true,
      opensAt: "08:00",
      closesAt: "12:00",
      physicalDifficulty: "Moderate",
      localGuidesAvailable: true,
      isFamilyFriendly: true,
      refundable: true,
      price: "1000",
    },
    {
      name: "Explore Red Fort",
      cityName: "New Delhi",
      duration: "3 hours",
      featured: true,
      opensAt: "10:00",
      closesAt: "16:00",
      physicalDifficulty: "Easy",
      localGuidesAvailable: true,
      isFamilyFriendly: true,
      refundable: true,
      price: "700",
    },
  ];
  
  export const discountData = {
    couponless: {
        applicableOn: { package: true },
        discountType: "couponless",
        userType: "all",
        noOfUsesPerUser: 10,
        noOfUsersTotal: 100,
        startDate: new Date().toISOString(),
        endDate: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString(),
        discountPercentage: 10,
        maxDiscount: 1000,
        noLimit: false,
        active: true,
        archived: false,
    },
    general: {
      applicableOn: { package: true },
      discountType: "general",
      userType: "all",
      noOfUsesPerUser: 5,
      noOfUsersTotal: 50,
      discountPercentage: 15,
      maxDiscount: 2000,
      noLimit: false,
      active: true,
      archived: false,
    },
  };
  

  export const destinationData2 = {
    name: 'Test Destination',
    currency: 'TST',
    timezone: 'UTC+05:00',
    tripDuration: ['3-5 days'],
    description: 'A destination for testing',
    visaType: 'tourist',
    country: 'Test Country',
    continent: 'Test Continent',
    latitude: 10.1234,
    longitude: 20.5678,
    markup: 15,
}

export const citiesDestinationData = {
    name: 'Test Destination',
    currency: 'TST',
    timezone: 'UTC+05:00',
    tripDuration: ['3-5 days'],
    description: 'A destination for testing',
    visaType: 'tourist',
    country: 'Test Country',
    continent: 'Test Continent',
    latitude: 10.1234,
    longitude: 20.5678,
    markup: 15,
  }

export const citiesData2 = {
    name: 'Test City for city',
    iataCode: 'TCT',
    country: 'Test Country',
    latitude: 15.6789,
    longitude: 25.1234,
    languageSpoken: 'English',
    hotelApiCityName: 'Test City for city'
  }

  export const activitiesData2 = {
    name: 'Test Activity',
    duration: '2 hours',
    featured: true,
    description: 'A test activity',
    opensAt: '09:00',
    closesAt: '17:00',
    cityName: 'Test City',
    bestTimeToParticipate: 'Morning',
    physicalDifficulty: 'Medium',
    localGuidesAvailable: true,
    isFamilyFriendly: true,
    refundable: true,
    price: 100.0,
  }

  export const adminPackageDestinationData =  {
    name: "Pakistan",
    currency: "PKR",
    timezone: "UTC+05:00",
    tripDuration: ["5-15 days"],
    description: "Discover the rich culture and breathtaking landscapes of Pakistan.",
    visaType: "tourist",
    country: "Pakistan",
    continent: "Asia",
    latitude: 30.3753,
    longitude: 69.3451,
    markup: 10,
}

export const detailsAdminPackageData =  {
    packageName: "Discover Pakistan",
    description: "An immersive travel experience through Pakistan.",
    totalDays: 7,
    startDate: "2024-12-01",
    itineraryStartDate: "2024-12-02",
    endDate: "2024-12-08",
    price: "60000",
    createdBy: {
        name: "Test User"
    },
    category: "OutdoorAdventures",
}